### PR TITLE
replace with new str method

### LINKED ISSUE #2025: [mojo-stdlib] Replace uses of `<foo>.__str__()` with `str(foo)`
### Review Mojo's priorities

- [X] I have read the [roadmap and priorities](https://docs.modular.com/mojo/roadmap.html#overall-priorities) and I believe this request falls within the priorities.

### What is your request?

There are still instances in the standard library that call dunder `str` function directly.  As of several Mojo versions ago, we introduced the `str(...)` function.  So, we can safely replace `foo.__str__()` with `str(foo)` everywhere.

### What is your motivation for this change?

Small refactoring for consistency/brevity.

### Any other details?

Some examples:

```
stdlib/src/builtin/error.mojo:        return self.__str__()
stdlib/src/pathlib/path.mojo:        return self.__str__() == other.__str__()
stdlib/test/python/test_ownership.mojo:        var py_string = my_list.__str__()
stdlib/test/python/test_ownership.mojo:        var py_string = my_tuple.__str__()
stdlib/test/python/test_ownership.mojo:    var py_string = obj.__str__()
stdlib/test/python/test_ownership.mojo:        var py_string = obj[1].__str__()
stdlib/test/python/test_ownership.mojo:        var py_string = obj.bar.__str__()
stdlib/test/python/test_python_to_mojo.mojo:    var cap_mojo_string = py_string_capitalized.__str__()
```

### PR DESCRIPTION
**Pull request by BreakTos**
Replaced every instance of foo._str_() with str(foo)
closes #2025

### CODE REVIEW

**Comment by JoeLoser** [comment]
Thanks for the contribution and even including the auto-close wording in the commit message so the GitHub issue will automatically close! Do you mind also modifying your commit message to include the signed-off part as mentioned in the contributing docs [here](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work)? Once you do that, I'll happily accept this contribution.

**Comment by BreakTos** [comment]
> Do you mind also modifying your commit message to include the signed-off part as mentioned in the 
Done sir!!

**Comment by JoeLoser** [comment]
Thanks for adding the signed-off part.  Right now, this PR is targeting to land into the `main` branch.  For development purposes, we want to submit PRs against the nightly branch as mentioned in the [docs](https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#pull-requests).  Do you mind changing this?  Locally, I think you'll want to rebase your branch against `nightly` and then, here in the Pull Request at the top, there is a way to select to change to merge into the `nightly` branch instead of `main` (currently it says "base: main").

Appreciate your enthusiasm and bear with us as we're working to make this clearer for everyone looking to contribute! 🚀

**Comment by BreakTos** [comment]
Making new PR in a moment

**Pull request closed without merging**
