### PR TITLE
[stdlib] DO NOT MERGE Reproducing  the bug introduced the 25/05/2024

### PR DESCRIPTION
**Pull request by gabrieldemarmiesse**

### CODE REVIEW

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
Confirmed repro and bissected back to https://github.com/modularml/modular/pull/40628#issuecomment-2132273990.  FYI @Mogball.

**Comment by JoeLoser** [comment]
Hey @gabrieldemarmiesse, would it be possible to rebase this branch so @Mogball has a latest reproducer to see if we can get over the hurdle to land this SBO work even with the extra byte in `List`?

**Comment by gabrieldemarmiesse** [comment]
Yeah I don't mind, but since this means I'll have to redo SBO once more, if we can wait for https://github.com/modularml/mojo/pull/2965 to land first that'd be great since it contains significant changes to `InlineArray`

**Comment by JoeLoser** [comment]
> Yeah I don't mind, but since this means I'll have to redo SBO once more, if we can wait for #2965 to land first that'd be great since it contains significant changes to `InlineArray`

#2965 landed in https://github.com/modularml/mojo/commit/990c776f830a9c098003eb05a61ececb764b28ee, so this should be good to rebase now.  Once this is rebased, we can work with @Mogball on any remaining compiler bugs for this work.

**Comment by gabrieldemarmiesse** [comment]
I tried to rebase my SSO work but I still get roadblocks, the big one currently is that `List` requires T to be `CollectionElement` while InlineArray requires T to be `CollectionElementNew` so we might want to tackle that before attempting to update SSO

**Comment by ConnorGray** [comment]
> the big one currently is that List requires T to be CollectionElement while InlineArray requires T to be CollectionElementNew so we might want to tackle that before attempting to update SSO

Apologies for this. This is work I started pushing on again today; I'm hoping to make meaningful progress on it by middle of next week.

**Comment by gabrieldemarmiesse** [comment]
I'd be happy to help if this can push the SSO work forward. I understand that basically, all collections should work with CollectionElementNew right? I can make a few PRs tomorrow and this weekend in this direction.

**Comment by JoeLoser** [comment]
> I'd be happy to help if this can push the SSO work forward. I understand that basically, all collections should work with CollectionElementNew right? I can make a few PRs tomorrow and this weekend in this direction.

FYI I undid this work for `InlineArray` and `Span` which will come out in today's nightly.  This might unblock some of the SSO work here where the explicit copyability got in the way a bit.

**Comment by JoeLoser** [comment]
Closing the PR to clean up the review queue as your other SSO PRs are the relevant ones still pending.

**Pull request closed without merging**
