### PR TITLE
Remove a redundant “from” in Variables

### PR DESCRIPTION
**Pull request by freespirit**

### CODE REVIEW

**Comment by arthurevans** [comment]
!sync

**Comment by JoeLoser** [comment]
@arthurevans do you mind working w/ the OP since this PR is targeting `main` and not `nightly` branch?

**Comment by freespirit** [comment]
@arthurevans I see the option to change the target branch to `nightly`, however I branched off of `main` and I'm not familiar with both histories... Should I branch from `nightly`, make the same change and open a new PR (dropping this one) instead?

**Comment by arthurevans** [comment]
@freespirit since it's just the one change, it's probably easier to open a new PR branched from nightly, yes.

**Comment by freespirit** [comment]
Hi again. I can't see the issue in nightly (https://github.com/modularml/mojo/blob/nightly/docs/manual/variables.ipynb), it looks like it was already fixed in https://github.com/modularml/mojo/commit/a749bd5df4da1162186bc6d83307df8439182348. I think we can just close this PR

**Pull request closed without merging**
