### PR TITLE
[docs] Fix the write your first Mojo program link

### PR DESCRIPTION
**Pull request by iamaliyousefi**
fix the **write your first Mojo program** link.

### CODE REVIEW

**Comment by JoeLoser** [comment]
Thanks for the contribution!  Do you mind modifying your commit message to include the signed-off part as mentioned in the contributing docs [here](https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#signing-your-work)?  Once you do that, feel free to ping here and I'll happily accept this contribution.

**Comment by iamaliyousefi** [comment]
Sorry for the missing signed-off part. I just added it.

**Review by arthurevans — APPROVED** [review]
LGTM. Thanks for the fix!

**Review by JoeLoser — CHANGES_REQUESTED** [review]
Do you mind rebasing/reopening your PR against the `nightly` branch, please? Requesting changes so this doesn't merge too quick into the `main` branch, where we're not welcoming contributions.

Right now, this PR is targeting to land into the main branch. For development purposes, we want to submit PRs against the nightly branch as mentioned in the [docs](https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#pull-requests). Do you mind changing this? Locally, I think you'll want to rebase your branch against nightly and then, here in the Pull Request at the top, there is a way to select to change to merge into the nightly branch instead of main (currently it says "base: main").

Appreciate your enthusiasm and bear with us as we're working to make this clearer for everyone looking to contribute! 🚀

**Comment by iamaliyousefi** [comment]
@JoeLoser  It got too complex. Just created a clean one. I'm closing this PR, in favor of #2040

**Pull request closed without merging**
