### PR TITLE
[stdlib] Introduce Hasher type with all necessary changes

### PR DESCRIPTION
**Pull request by mzaks**
This is a draft because although the code compiles 8 tests are failing.
It might be due to compiler bug. The error messages are cryptic. I don't have the "Mojo" ;) to fix them.

Failed Tests (8):
  Mojo Standard Library :: builtin/test_dtype.mojo
  Mojo Standard Library :: builtin/test_hash.mojo
  Mojo Standard Library :: builtin/test_object.mojo
  Mojo Standard Library :: builtin/test_string.mojo
  Mojo Standard Library :: builtin/test_string_literal.mojo
  Mojo Standard Library :: collections/test_dict.mojo
  Mojo Standard Library :: collections/test_set.mojo
  Mojo Standard Library :: python/test_python_object.mojo

### CODE REVIEW

**Comment by mzaks** [comment]
Minimal example to reproduce the issue:
https://github.com/mzaks/mojo/tree/feature/minimal-example-of-test-crash-for-new-hasher

**Comment by mzaks** [comment]
@JoeLoser do we have a status on this one? From what I can tell there are some unexpected deeper language problems, my guess is it has something to do with register passable types. I am ok with shelving it for now. If so, I will concentrate on some other things and revisit when it is resolvable.

**Comment by mzaks** [comment]
Actually now I the minimal reproducible example [mzaks:feature/minimal-example-of-test-crash-for-new-hasher](https://github.com/mzaks/mojo/tree/feature/minimal-example-of-test-crash-for-new-hasher) and it some times passes and some times fails the test. Seems like the order of tests is important and there is something fishy going on.

**Comment by mzaks** [comment]
After rebasing the [mzaks:feature/minimal-example-of-test-crash-for-new-hasher](https://github.com/mzaks/mojo/tree/feature/minimal-example-of-test-crash-for-new-hasher) on todays nightly, I see following compile error on :

```
invalid indirect call: l-value of type '$0' cannot be converted to reference of type 'H'
struct Int(
       ^~~
```

The `H` in question is from:
```
trait NewHashable:
    fn __hash_with__[H: Hasher](self, inout hasher: H):
        pass
```

which `Int` is implementing.

I pushed the rebased version so the team can confirm.

**Comment by helehex** [comment]
I noticed there is a private `_Hasher` trait in the stdlib now?

**Comment by mzaks** [comment]
> I noticed there is a private `_Hasher` trait in the stdlib now?

Yeah this is some incremental work done by @gabrieldemarmiesse 

But his effort is also stuck on following issue https://github.com/modularml/mojo/issues/2892

**Comment by JoeLoser** [comment]
@mzaks should we close this PR in favor of your recent PRs that have landed?

**Comment by mzaks** [comment]
> @mzaks should we close this PR in favor of your recent PRs that have landed?

Yes please! I am traveling till the end of the week, I intend to add one more PR to tighten up the Hasher support and retire the previous hash mechanism next week.

**Comment by JoeLoser** [comment]
> > @mzaks should we close this PR in favor of your recent PRs that have landed?
> 
> Yes please! I am traveling till the end of the week, I intend to add one more PR to tighten up the Hasher support and retire the previous hash mechanism next week.

Awesome, thanks for all of your hard work in this area! 🔥

**Pull request closed without merging**
