### PR TITLE
Update types.ipynb , fixed typo

### PR DESCRIPTION
**Pull request by mcroni**

### CODE REVIEW

**Review by KenJones-Modular — APPROVED** [review]

**Comment by JoeLoser** [comment]
Thanks for the fix. Do you mind targeting the nightly branch instead as the [docs](https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#pull-requests) say? Otherwise, we won't be able to import this PR and merge it.

**Comment by mcroni** [comment]
can't seem to push to nightly

**Comment by JoeLoser** [comment]
> can't seem to push to nightly

Did you follow along at https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#branching-off-nightly?  You want to push to a local branch on your remote/fork - you can call that branch whatever you want as long as it's based off of the `nightly` branch from `modularml/mojo` repo.

**Comment by Brian-M-J** [comment]
Actually, it seems this has already been fixed in the `nightly` branch (by me 😅). See [commit 565586f](https://github.com/modularml/mojo/commit/565586fcda0b7b0db4a40efe593af28618bd6589#diff-013bed940feb94fa25ae4e5d30fb4b4fd45718daaf87a47d81043fc5181c618aL747)

**Comment by JoeLoser** [comment]
> Actually, it seems this has already been fixed in the `nightly` branch (by me 😅). See [commit 565586f](https://github.com/modularml/mojo/commit/565586fcda0b7b0db4a40efe593af28618bd6589#diff-013bed940feb94fa25ae4e5d30fb4b4fd45718daaf87a47d81043fc5181c618aL747)

Thanks - closing as such.

**Pull request closed without merging**
