### PR TITLE
Add proposal for the new ref conventions

### PR DESCRIPTION
**Pull request by nmsmith**
This is the proposal for the new ref conventions that Chris and I have been working on.

I'm publishing this now at Chris's request. 🙂

Modular folks: please let me know if I should start a Github discussion pointing to this PR, or if it should be merged first. (Feel free to post the discussion thread on my behalf. I might be sleeping. 😴)

### CODE REVIEW

**Comment by nmsmith** [comment]
@lattner I force-pushed a new commit that is correctly signed. This integrates the edits that you made.

**Comment by JoeLoser** [comment]
Hey guys, thanks for the proposal!  Proposals are still pushed out through our copybara process, so I'll sync this PR internally now.

**Comment by JoeLoser** [comment]
!sync

**Comment by JoeLoser** [comment]
Actually, @nmsmith - do you mind targeting the `nightly` branch as shown in the [contributing docs](https://github.com/modularml/mojo/blob/nightly/CONTRIBUTING.md#pull-requests) so this can be imported internally, please?  Thanks!

**Comment by nmsmith** [comment]
@JoeLoser Oh ok, sure. I was just copying where Chris put his last PR 😇. I've opened a new PR: #2872.

**Comment by gabrieldemarmiesse** [comment]
Linking https://github.com/modularml/mojo/issues/2556 here since it seems a recurring issue

**Pull request closed without merging**
