### PR TITLE
Update issue templates to allow markdown

### PR DESCRIPTION
**Pull request by mojodojodev**
Currently when raising an issue or feature request, many of the inputs have the `shell` render type, which wraps the input in a code block with the `shell` language, you then have to go in and edit it after submitting. 

Removing these `render: shell` options makes it so you get the full markdown editor for the input, and can include your own code blocks as well as links and styling etc.

### CODE REVIEW

**Comment by lattner** [comment]
I don't know how this works, @goldiegadde can you take a look next week when you're back?

**Comment by mojodojodev** [comment]
I'll put screenshots here to show exactly how it works pre and post change if that helps:

## Pre Change (with `render:shell`)
### Entering Bug
image

### Result
image

Can see the editor was in plain text mode and inserts a code block like:

\`\`\`shell
this is a box where I might want to put code examples

x = 10
print(x)
\`\`\`

## Post Change (without `render:shell`)
### Entering Bug
image

### Result
image

Removing `render:shell` gives us the full markdown editor with formatting options where you can write plaintext or put code blocks in and get syntax highlighting.

**Review by scottamain — APPROVED** [review]

**Comment by gryznar** [comment]
@scottamain can it be merged? I suppose that normal users do not have proper privillege :)

**Comment by Mogball** [comment]
This should be landed. I've been wondering for a while why the issue templates looked so strange...

**Review by goldiegadde — APPROVED** [review]

**Pull request merged**
