### PR TITLE
Fix: typos in readme. 

### PR DESCRIPTION
**Pull request by moli-debugger**

### CODE REVIEW

**Comment by gryznar** [comment]
Title of this pr also has typos. I propose:
`Fix: Hanled typo error in read me file` -> `Fix typos in README`

**Comment by moli-debugger** [comment]
Thanks updated the same.

**Review by arthurevans — CHANGES_REQUESTED** [review]
A couple of minor comments, but mainly to merge this we'd need to revert the formatting change (text should be wrapped as before) and fix the DCO issue (commit doesn't appear to be signed correctly).

**Comment by JoeLoser** [comment]
@arthurevans do you mind working w/ the OP since this PR is targeting `main` and not `nightly` branch?

**Comment by arthurevans** [comment]
Hi @moli-debugger. If you want to continue with this, can you open a new PR against nightly, and make sure it's signed off? Please see the PR instructions here:

https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#pull-request-process

**Comment by JoeLoser** [comment]
> Hi @moli-debugger. If you want to continue with this, can you open a new PR against nightly, and make sure it's signed off? Please see the PR instructions here:
> 
> https://github.com/modularml/mojo/blob/main/CONTRIBUTING.md#pull-request-process

I'm going to close this PR to help clean up the review queue.  But like Arthur said, feel free to reopen a PR against the `nightly` branch. Thanks!

**Pull request closed without merging**
